#!/bin/sh

# Usage: build has_native

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1

add lib pkg/META		
add lib src/rtime.mli
add lib src/rtime.cmti
add lib src/rtime.cmi
add lib src/rtime.cmx
add lib src/rtime.cma
add lib src/rtime.a
add lib src/rtime.cmxa
add lib src/rtime.cmxs

add doc README.md
add doc CHANGES.md
add doc test/examples.ml examples.ml

build
install rtime
